/**
 * YouTube transcript fetcher — caption-track scrape with optional Apify fallback.
 *
 * Strategy (matches Smart-Scale's `getYouTubeTranscript` flow):
 *   1. If APIFY_API_TOKEN is set, try the `automation-lab~youtube-transcript`
 *      actor which handles login walls + age-restricted videos better.
 *   2. Fall back to scraping `youtube.com/watch?v=`, extracting
 *      `ytInitialPlayerResponse`, picking a caption track (preferring English)
 *      and parsing its srv3 XML.
 *
 * No YouTube Data API key required for transcript — only for metadata
 * (see `getYouTubeMetadata`, which is optional).
 */

const APIFY_BASE = 'https://api.apify.com/v2'
const APIFY_YT_ACTOR = 'automation-lab~youtube-transcript'

export interface YouTubeTranscriptResult {
  transcript: string | null
  /** 'apify' | 'watch_page' | null when both failed. */
  provider: 'apify' | 'watch_page' | null
  /** Hint for the caller — e.g. 'login_required', 'no_captions_found'. */
  reason?: string
}

export interface YouTubeMetadata {
  title: string | null
  creator: string | null
  thumbnail: string | null
  duration: string | null
}

// ─── URL → videoId ───────────────────────────────────────────────────────────

const YT_PATTERNS = [
  /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([^&\n?#]+)/,
  /youtube\.com\/shorts\/([^&\n?#]+)/,
]

export function extractYouTubeId(url: string): string | null {
  for (const p of YT_PATTERNS) {
    const m = url.match(p)
    if (m) return m[1] ?? null
  }
  return null
}

export function isYouTubeUrl(url: string): boolean {
  return /youtube\.com|youtu\.be/.test(url)
}

// ─── Caption XML parsing ─────────────────────────────────────────────────────

function decodeHtmlEntities(value: string): string {
  return value
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
}

function stripXmlTags(value: string): string {
  return decodeHtmlEntities(value)
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function parseCaptionXml(xml: string): string | null {
  const textMatches = [...xml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/gi)]
  if (textMatches.length) {
    const text = textMatches
      .map((m) => stripXmlTags(m[1] ?? ''))
      .filter(Boolean)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim()
    return text || null
  }

  const paragraphMatches = [...xml.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)]
  if (paragraphMatches.length) {
    const text = paragraphMatches
      .map((m) => {
        const inner = m[1] ?? ''
        const segs = [...inner.matchAll(/<s\b[^>]*>([\s\S]*?)<\/s>/gi)]
        if (segs.length) {
          return segs
            .map((s) => stripXmlTags(s[1] ?? ''))
            .filter(Boolean)
            .join(' ')
        }
        return stripXmlTags(inner)
      })
      .filter(Boolean)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim()
    return text || null
  }

  return null
}

interface PlayerResponse {
  playabilityStatus?: { status?: string; reason?: string }
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{ baseUrl?: string; languageCode?: string; kind?: string }>
    }
  }
  videoDetails?: { title?: string; author?: string; lengthSeconds?: string; thumbnail?: { thumbnails?: Array<{ url: string }> } }
}

function extractPlayerResponse(html: string): PlayerResponse | null {
  const patterns = [
    /ytInitialPlayerResponse\s*=\s*(\{[\s\S]*?\})\s*;/,
    /window\[["']ytInitialPlayerResponse["']\]\s*=\s*(\{[\s\S]*?\})\s*;/,
  ]
  for (const p of patterns) {
    const m = html.match(p)
    if (!m?.[1]) continue
    try {
      return JSON.parse(m[1]) as PlayerResponse
    } catch {
      continue
    }
  }
  return null
}

// ─── Transcript fetchers ─────────────────────────────────────────────────────

async function fetchFromApify(videoId: string): Promise<YouTubeTranscriptResult> {
  const token = process.env.APIFY_API_TOKEN
  if (!token) return { transcript: null, provider: null, reason: 'apify_no_token' }

  try {
    const res = await fetch(
      `${APIFY_BASE}/acts/${APIFY_YT_ACTOR}/run-sync-get-dataset-items?token=${token}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          urls: [`https://www.youtube.com/watch?v=${videoId}`],
          language: 'en',
          includeAutoGenerated: true,
          mergeSegments: true,
        }),
        signal: AbortSignal.timeout(120_000),
      },
    )
    if (!res.ok) {
      return { transcript: null, provider: 'apify', reason: `apify_http_${res.status}` }
    }
    const data = (await res.json()) as Array<Record<string, unknown>>
    const item = data?.[0]
    if (!item) return { transcript: null, provider: 'apify', reason: 'apify_empty' }

    const candidates = [
      item.fullText,
      item.transcript,
      item.text,
      item.captionsText,
      item.subtitlesText,
      Array.isArray(item.segments)
        ? (item.segments as Array<{ text?: string }>)
            .map((s) => s?.text)
            .filter(Boolean)
            .join(' ')
        : null,
    ]
    const transcript =
      candidates.find((v) => typeof v === 'string' && v.trim()) as string | undefined
    if (transcript) return { transcript: transcript.trim(), provider: 'apify' }

    const itemError = typeof item.error === 'string' ? item.error.toLowerCase() : ''
    const reason =
      itemError.includes('login') ||
      itemError.includes('age-restricted') ||
      itemError.includes('private')
        ? 'login_required'
        : 'no_captions_found'
    return { transcript: null, provider: 'apify', reason }
  } catch (err) {
    return {
      transcript: null,
      provider: 'apify',
      reason: 'apify_exception:' + (err instanceof Error ? err.message : String(err)),
    }
  }
}

async function fetchFromWatchPage(videoId: string): Promise<YouTubeTranscriptResult> {
  try {
    const watchRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0',
        'Accept-Language': 'en-US,en;q=0.9',
      },
      signal: AbortSignal.timeout(20_000),
    })
    if (!watchRes.ok) {
      return { transcript: null, provider: 'watch_page', reason: `watch_http_${watchRes.status}` }
    }
    const html = await watchRes.text()
    const playerResponse = extractPlayerResponse(html)
    const status = playerResponse?.playabilityStatus?.status
    const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
    if (!tracks.length) {
      return {
        transcript: null,
        provider: 'watch_page',
        reason: status === 'LOGIN_REQUIRED' ? 'login_required' : 'no_caption_tracks',
      }
    }

    const preferred =
      tracks.find((t) => t.languageCode === 'en') ??
      tracks.find((t) => t.languageCode?.startsWith('en')) ??
      tracks.find((t) => !t.kind) ??
      tracks[0]
    if (!preferred?.baseUrl) {
      return { transcript: null, provider: 'watch_page', reason: 'caption_track_no_base_url' }
    }

    const captionUrl = preferred.baseUrl.includes('fmt=')
      ? preferred.baseUrl
      : `${preferred.baseUrl}&fmt=srv3`
    const capRes = await fetch(captionUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0',
        'Accept-Language': 'en-US,en;q=0.9',
      },
      signal: AbortSignal.timeout(20_000),
    })
    if (!capRes.ok) {
      return { transcript: null, provider: 'watch_page', reason: `caption_http_${capRes.status}` }
    }
    const xml = await capRes.text()
    const transcript = parseCaptionXml(xml)
    if (!transcript) {
      return { transcript: null, provider: 'watch_page', reason: 'caption_parse_failed' }
    }
    return { transcript, provider: 'watch_page' }
  } catch (err) {
    return {
      transcript: null,
      provider: 'watch_page',
      reason: 'watch_exception:' + (err instanceof Error ? err.message : String(err)),
    }
  }
}

/**
 * Get a YouTube transcript using Apify if available, else scrape watch page.
 * Returns transcript=null if both providers fail.
 */
export async function getYouTubeTranscript(videoId: string): Promise<YouTubeTranscriptResult> {
  const apifyResult = await fetchFromApify(videoId)
  if (apifyResult.transcript) return apifyResult

  const watchResult = await fetchFromWatchPage(videoId)
  if (watchResult.transcript) return watchResult

  // Prefer the more meaningful failure reason for the caller.
  const preferred =
    watchResult.reason === 'login_required' || watchResult.reason === 'no_caption_tracks'
      ? watchResult
      : apifyResult.reason
        ? apifyResult
        : watchResult
  return { transcript: null, provider: preferred.provider, reason: preferred.reason }
}

/**
 * Best-effort metadata from the watch page (no YouTube Data API key required).
 * Returns nulls for fields that couldn't be parsed.
 */
export async function getYouTubeMetadataFromWatchPage(videoId: string): Promise<YouTubeMetadata> {
  try {
    const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0',
        'Accept-Language': 'en-US,en;q=0.9',
      },
      signal: AbortSignal.timeout(15_000),
    })
    if (!res.ok) return { title: null, creator: null, thumbnail: null, duration: null }

    const html = await res.text()
    const player = extractPlayerResponse(html)
    const details = player?.videoDetails

    let duration: string | null = null
    const seconds = details?.lengthSeconds ? Number(details.lengthSeconds) : NaN
    if (Number.isFinite(seconds) && seconds > 0) {
      const h = Math.floor(seconds / 3600)
      const m = Math.floor((seconds % 3600) / 60)
      const s = String(Math.round(seconds % 60)).padStart(2, '0')
      duration = h > 0
        ? `${h}:${String(m).padStart(2, '0')}:${s}`
        : `${m}:${s}`
    }

    const thumbnails = details?.thumbnail?.thumbnails ?? []
    const thumbnail = thumbnails[thumbnails.length - 1]?.url ?? null

    return {
      title: details?.title ?? null,
      creator: details?.author ?? null,
      thumbnail,
      duration,
    }
  } catch {
    return { title: null, creator: null, thumbnail: null, duration: null }
  }
}
